### ISSUE TITLE
docker-compose extends?

### ISSUE THREAD

**Issue by claydiffrient** [FreedomBen/gimme-dat-canvas#1]
Any advantage of recommending people include `canvas-` containers (essentially duplicating the canvas-lms docker-compose file) inside their own docker-compose?

Why not just extend it from within your own docker-compose (https://docs.docker.com/compose/extends/#extending-services) ?

So in theory (read: I haven't tried it), you should be able to recommend doing something like this:

```
# My own projects docker-compose.yml
canvas:
  extends:
    file: path/to/canvas-lms/docker-compose.yml
    service: web
```

Thoughts?
